[project]
name = "hexlet-h"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "more-itertools>=10.7.0",
    "pydf>=12",
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
